"""Add email and description columns

Revision ID: ed0908a1cc6f
Revises: 808b6df1b7a0
Create Date: 2025-09-25 17:49:39.006691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed0908a1cc6f'
down_revision = '808b6df1b7a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_artists')
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_artists_email'), ['email'], unique=True)
        batch_op.create_unique_constraint('uq_artists_email', ['email'])

    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_constraint('uq_artists_email', type_='unique')
        batch_op.drop_index(batch_op.f('ix_artists_email'))
        batch_op.drop_column('email')

    op.create_table('_alembic_tmp_artists',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('profile_pic', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('bio', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name=op.f('uq_artists_email'))
    )
    # ### end Alembic commands ###
